# Dataset Information

Dataset: Electricity prices for household consumers (nrg_pc_204)

Source: Eurostat.

License: Eurostat reuse policy.

Access method: Eurostat API via the `eurostat` Python package.

Link: https://ec.europa.eu/eurostat/databrowser/view/nrg_pc_204/default/table?lang=en

In [1]:
## Installing eurostat library in case it doesn't exist
#%pip install eurostat

## Load dataset

In [2]:
import eurostat

df = eurostat.get_data_df("nrg_pc_204")

## Saving raw dataset

In [3]:
df.to_csv(
    "../data/raw/eurostat_energy_prices.csv",
    index=False
)

## Data checks and transformation

In [4]:
df.columns.tolist()

['freq',
 'siec',
 'nrg_cons',
 'unit',
 'tax',
 'currency',
 'geo\\TIME_PERIOD',
 '2007-S1',
 '2007-S2',
 '2008-S1',
 '2008-S2',
 '2009-S1',
 '2009-S2',
 '2010-S1',
 '2010-S2',
 '2011-S1',
 '2011-S2',
 '2012-S1',
 '2012-S2',
 '2013-S1',
 '2013-S2',
 '2014-S1',
 '2014-S2',
 '2015-S1',
 '2015-S2',
 '2016-S1',
 '2016-S2',
 '2017-S1',
 '2017-S2',
 '2018-S1',
 '2018-S2',
 '2019-S1',
 '2019-S2',
 '2020-S1',
 '2020-S2',
 '2021-S1',
 '2021-S2',
 '2022-S1',
 '2022-S2',
 '2023-S1',
 '2023-S2',
 '2024-S1',
 '2024-S2',
 '2025-S1',
 '2025-S2']

In [5]:
df.shape

(2196, 45)

In [6]:
df.head(10)

,freq,siec,nrg_cons,unit,tax,currency,geo\TIME_PERIOD,2007-S1,2007-S2,2008-S1,...,2021-S1,2021-S2,2022-S1,2022-S2,2023-S1,2023-S2,2024-S1,2024-S2,2025-S1,2025-S2
0,S,E7000,KWH1000-2499,KWH,I_TAX,EUR,AL,NaN,NaN,NaN,...,0.0925,0.0937,0.0941,0.0976,0.1010,0.1089,0.1114,0.1150,0.1156,0.1175
1,S,E7000,KWH1000-2499,KWH,I_TAX,EUR,AT,NaN,0.2008,0.2005,...,0.2650,0.2787,0.2616,0.2614,0.2988,0.3055,0.3011,0.2631,0.3165,0.3669
2,S,E7000,KWH1000-2499,KWH,I_TAX,EUR,BA,NaN,NaN,NaN,...,0.0980,0.0970,0.0996,0.1003,0.1043,0.0990,0.1067,0.1054,0.1100,0.1125
3,S,E7000,KWH1000-2499,KWH,I_TAX,EUR,BE,NaN,0.1867,0.2172,...,0.2910,0.3161,0.3633,0.4586,0.4559,0.4111,0.3715,0.3695,0.3939,0.3806
4,S,E7000,KWH1000-2499,KWH,I_TAX,EUR,BG,NaN,0.0721,0.0731,...,0.1045,0.1104,0.1110,0.1147,0.1146,0.1192,0.1193,0.1224,0.1313,0.1355
5,S,E7000,KWH1000-2499,KWH,I_TAX,EUR,CY,NaN,0.1554,0.1757,...,0.2125,0.2451,0.2724,0.3377,0.3909,0.3635,0.3432,0.3452,0.3131,0.2995
6,S,E7000,KWH1000-2499,KWH,I_TAX,EUR,CZ,0.1573,0.1618,0.1889,...,0.2398,0.2437,0.2903,0.0961,0.3724,0.3685,0.3974,0.3910,0.3893,0.3921
7,S,E7000,KWH1000-2499,KWH,I_TAX,EUR,DE,0.2258,0.2340,0.2389,...,0.3527,0.3588,0.3643,0.3738,0.4536,0.4458,0.4423,0.4433,0.4347,0.4383
8,S,E7000,KWH1000-2499,KWH,I_TAX,EUR,DK,NaN,0.2676,0.2920,...,0.3131,0.3690,0.4798,0.6095,0.4086,0.3801,0.3972,0.4028,0.3759,0.3578
9,S,E7000,KWH1000-2499,KWH,I_TAX,EUR,EA,0.2138,0.1746,0.1733,...,0.2635,0.2844,0.2851,0.3134,0.3349,0.3376,0.3417,0.3422,0.3419,0.3450

### Years here are splitted (for example 2007-S1, 2007-S2 which means semi-annual. For analysis these values will be aggregated)

In [7]:
sorted(df["geo\\TIME_PERIOD"].unique())

['AL',
 'AT',
 'BA',
 'BE',
 'BG',
 'CY',
 'CZ',
 'DE',
 'DK',
 'EA',
 'EE',
 'EL',
 'ES',
 'EU27_2020',
 'FI',
 'FR',
 'GE',
 'HR',
 'HU',
 'IE',
 'IS',
 'IT',
 'LI',
 'LT',
 'LU',
 'LV',
 'MD',
 'ME',
 'MK',
 'MT',
 'NL',
 'NO',
 'PL',
 'PT',
 'RO',
 'RS',
 'SE',
 'SI',
 'SK',
 'TR',
 'UA',
 'UK',
 'XK']

### From country list what interests us are "PL", and "EU27_2020".

In [8]:
df.isna().sum()

freq                  0
siec                  0
nrg_cons              0
unit                  0
tax                   0
currency              0
geo\TIME_PERIOD       0
2007-S1            1902
2007-S2             855
2008-S1             816
2008-S2             816
2009-S1             807
2009-S2             807
2010-S1             798
2010-S2             783
2011-S1             693
2011-S2             693
2012-S1             612
2012-S2             567
2013-S1             492
2013-S2             492
2014-S1             462
2014-S2             462
2015-S1             432
2015-S2             432
2016-S1             402
2016-S2             402
2017-S1             396
2017-S2             375
2018-S1             390
2018-S2             345
2019-S1             345
2019-S2             345
2020-S1             327
2020-S2             372
2021-S1             363
2021-S2              99
2022-S1             135
2022-S2              90
2023-S1              99
2023-S2              99
2024-S1             144
2024-S2             108
2025-S1             135
2025-S2             144
dtype: int64

### There are some missing values in years. Let's filter out Poland and EU27 to see whether there are still some missings

In [9]:
selected_countries = df["geo\\TIME_PERIOD"].isin(["PL","EU27_2020"])
filtered_df = df[selected_countries]

In [10]:
filtered_df.isna().sum()

freq                0
siec                0
nrg_cons            0
unit                0
tax                 0
currency            0
geo\TIME_PERIOD     0
2007-S1            75
2007-S2            30
2008-S1            30
2008-S2            30
2009-S1            30
2009-S2            30
2010-S1            30
2010-S2            30
2011-S1            30
2011-S2            30
2012-S1            30
2012-S2            30
2013-S1            30
2013-S2            30
2014-S1            30
2014-S2            30
2015-S1            30
2015-S2            30
2016-S1            30
2016-S2            30
2017-S1            15
2017-S2             9
2018-S1             9
2018-S2             9
2019-S1             9
2019-S2             9
2020-S1             9
2020-S2             9
2021-S1             9
2021-S2             0
2022-S1             0
2022-S2             0
2023-S1             0
2023-S2             0
2024-S1             9
2024-S2             0
2025-S1             9
2025-S2             0
dtype: int64

### There are still missing values. Performing additional checks.

In [11]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 13 to 2188
Data columns (total 45 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   freq             90 non-null     object
 1   siec             90 non-null     object
 2   nrg_cons         90 non-null     object
 3   unit             90 non-null     object
 4   tax              90 non-null     object
 5   currency         90 non-null     object
 6   geo\TIME_PERIOD  90 non-null     object
 7   2007-S1          15 non-null     float64
 8   2007-S2          60 non-null     float64
 9   2008-S1          60 non-null     float64
 10  2008-S2          60 non-null     float64
 11  2009-S1          60 non-null     float64
 12  2009-S2          60 non-null     float64
 13  2010-S1          60 non-null     float64
 14  2010-S2          60 non-null     float64
 15  2011-S1          60 non-null     float64
 16  2011-S2          60 non-null     float64
 17  2012-S1          60 non-null     float64
 18  2012-S2          60 non-null     float64
 19  2013-S1          60 non-null     float64
 20  2013-S2          60 non-null     float64
 21  2014-S1          60 non-null     float64
 22  2014-S2          60 non-null     float64
 23  2015-S1          60 non-null     float64
 24  2015-S2          60 non-null     float64
 25  2016-S1          60 non-null     float64
 26  2016-S2          60 non-null     float64
 27  2017-S1          75 non-null     float64
 28  2017-S2          81 non-null     float64
 29  2018-S1          81 non-null     float64
 30  2018-S2          81 non-null     float64
 31  2019-S1          81 non-null     float64
 32  2019-S2          81 non-null     float64
 33  2020-S1          81 non-null     float64
 34  2020-S2          81 non-null     float64
 35  2021-S1          81 non-null     float64
 36  2021-S2          90 non-null     float64
 37  2022-S1          90 non-null     float64
 38  2022-S2          90 non-null     float64
 39  2023-S1          90 non-null     float64
 40  2023-S2          90 non-null     float64
 41  2024-S1          81 non-null     float64
 42  2024-S2          90 non-null     float64
 43  2025-S1          81 non-null     float64
 44  2025-S2          90 non-null     float64
dtypes: float64(38), object(7)
memory usage: 32.3+ KB

In [12]:
filtered_df.shape

(90, 45)

In [13]:
filtered_df.head(10)

,freq,siec,nrg_cons,unit,tax,currency,geo\TIME_PERIOD,2007-S1,2007-S2,2008-S1,...,2021-S1,2021-S2,2022-S1,2022-S2,2023-S1,2023-S2,2024-S1,2024-S2,2025-S1,2025-S2
13,S,E7000,KWH1000-2499,KWH,I_TAX,EUR,EU27_2020,0.1974,0.1707,0.1714,...,0.2492,0.2719,0.2725,0.2981,0.3152,0.3135,0.3245,0.3245,0.3239,0.3303
32,S,E7000,KWH1000-2499,KWH,I_TAX,EUR,PL,NaN,0.1408,0.1329,...,0.1702,0.1740,0.1608,0.1767,0.1992,0.2102,0.2027,0.2544,0.2709,0.2928
74,S,E7000,KWH1000-2499,KWH,I_TAX,NAC,PL,NaN,0.5244,0.4641,...,0.7722,0.7988,0.7456,0.8370,0.9207,0.9376,0.8750,1.0927,1.1462,1.2435
98,S,E7000,KWH1000-2499,KWH,I_TAX,PPS,EU27_2020,NaN,NaN,NaN,...,0.2492,0.2648,0.2733,0.2997,0.3132,0.3097,0.3169,0.3185,0.3228,0.3308
114,S,E7000,KWH1000-2499,KWH,I_TAX,PPS,PL,NaN,0.2309,0.1953,...,0.2882,0.2902,0.2569,0.2884,0.3197,0.3256,0.2852,0.3561,0.3701,0.4015
136,S,E7000,KWH1000-2499,KWH,X_TAX,EUR,EU27_2020,0.1333,0.1246,0.1261,...,0.1597,0.1837,0.2202,0.2675,0.2703,0.2566,0.2561,0.2539,0.2422,0.2429
155,S,E7000,KWH1000-2499,KWH,X_TAX,EUR,PL,NaN,0.1088,0.1016,...,0.1006,0.0967,0.0991,0.1093,0.1021,0.1114,0.1003,0.1455,0.1583,0.1653
197,S,E7000,KWH1000-2499,KWH,X_TAX,NAC,PL,NaN,0.4051,0.3549,...,0.4564,0.4441,0.4594,0.5178,0.4719,0.4969,0.4331,0.6250,0.6697,0.7020
221,S,E7000,KWH1000-2499,KWH,X_TAX,PPS,EU27_2020,NaN,NaN,NaN,...,0.1604,0.1799,0.2206,0.2685,0.2659,0.2515,0.2497,0.2488,0.2403,0.2425
237,S,E7000,KWH1000-2499,KWH,X_TAX,PPS,PL,NaN,0.1783,0.1493,...,0.1703,0.1613,0.1583,0.1784,0.1639,0.1726,0.1411,0.2037,0.2162,0.2267

### In data there are different currencies. Checking other dimensions.

In [14]:
sorted(filtered_df["freq"].unique())

['S']

In [15]:
sorted(filtered_df["siec"].unique())

['E7000']

In [16]:
sorted(filtered_df["nrg_cons"].unique())

['KWH1000-2499',
 'KWH2500-4999',
 'KWH5000-14999',
 'KWH_GE15000',
 'KWH_LT1000',
 'TOT_KWH']

### nrg_cons contains ranges of consumed energy by a household. For the analysis there is planned to be no distinctions, therefore "TOT_KWH" (total usage) will be used.

In [17]:
sorted(filtered_df["unit"].unique())

['KWH']

In [18]:
sorted(filtered_df["tax"].unique())

['I_TAX', 'X_TAX', 'X_VAT']

### "I_TAX" includes all taxes and levies. As the citizen pays for electricity with tax it will be chosen for the analysis.

In [19]:
sorted(filtered_df["geo\TIME_PERIOD"].unique())

['EU27_2020', 'PL']

In [20]:
sorted(filtered_df["currency"].unique())

['EUR', 'NAC', 'PPS']

### For  the analysis Euro will be taken.

In [21]:
selected_tax = filtered_df["tax"].isin(["I_TAX"])
selected_currency = filtered_df["currency"].isin(["EUR"])
selected_nrg = filtered_df["nrg_cons"].isin(["TOT_KWH"])

#Updating filtered_df
filtered_df_detailed = filtered_df[
    selected_tax &
    selected_currency &
    selected_nrg
]
filtered_df_detailed.head(10)

,freq,siec,nrg_cons,unit,tax,currency,geo\TIME_PERIOD,2007-S1,2007-S2,2008-S1,...,2021-S1,2021-S2,2022-S1,2022-S2,2023-S1,2023-S2,2024-S1,2024-S2,2025-S1,2025-S2
1858,S,E7000,TOT_KWH,KWH,I_TAX,EUR,EU27_2020,NaN,NaN,NaN,...,0.1562,0.2400,0.2491,0.2764,0.2919,0.2906,0.2969,0.2941,0.2949,0.2942
1877,S,E7000,TOT_KWH,KWH,I_TAX,EUR,PL,NaN,NaN,NaN,...,NaN,0.1654,0.1530,0.1709,0.1979,0.2291,NaN,0.2573,NaN,0.2854

In [22]:
filtered_df_detailed.isna().sum()

freq               0
siec               0
nrg_cons           0
unit               0
tax                0
currency           0
geo\TIME_PERIOD    0
2007-S1            2
2007-S2            2
2008-S1            2
2008-S2            2
2009-S1            2
2009-S2            2
2010-S1            2
2010-S2            2
2011-S1            2
2011-S2            2
2012-S1            2
2012-S2            2
2013-S1            2
2013-S2            2
2014-S1            2
2014-S2            2
2015-S1            2
2015-S2            2
2016-S1            2
2016-S2            2
2017-S1            2
2017-S2            1
2018-S1            1
2018-S2            1
2019-S1            1
2019-S2            1
2020-S1            1
2020-S2            1
2021-S1            1
2021-S2            0
2022-S1            0
2022-S2            0
2023-S1            0
2023-S2            0
2024-S1            1
2024-S2            0
2025-S1            1
2025-S2            0
dtype: int64

In [23]:
filtered_df_detailed.transpose()

                      1858     1877
freq                     S        S
siec                 E7000    E7000
nrg_cons           TOT_KWH  TOT_KWH
unit                   KWH      KWH
tax                  I_TAX    I_TAX
currency               EUR      EUR
geo\TIME_PERIOD  EU27_2020       PL
2007-S1                NaN      NaN
2007-S2                NaN      NaN
2008-S1                NaN      NaN
2008-S2                NaN      NaN
2009-S1                NaN      NaN
2009-S2                NaN      NaN
2010-S1                NaN      NaN
2010-S2                NaN      NaN
2011-S1                NaN      NaN
2011-S2                NaN      NaN
2012-S1                NaN      NaN
2012-S2                NaN      NaN
2013-S1                NaN      NaN
2013-S2                NaN      NaN
2014-S1                NaN      NaN
2014-S2                NaN      NaN
2015-S1                NaN      NaN
2015-S2                NaN      NaN
2016-S1                NaN      NaN
2016-S2                NaN      NaN
2017-S1                NaN      NaN
2017-S2             0.1524      NaN
2018-S1             0.1782      NaN
2018-S2             0.1743      NaN
2019-S1              0.208      NaN
2019-S2             0.2021      NaN
2020-S1             0.1572      NaN
2020-S2             0.1639      NaN
2021-S1             0.1562      NaN
2021-S2               0.24   0.1654
2022-S1             0.2491    0.153
2022-S2             0.2764   0.1709
2023-S1             0.2919   0.1979
2023-S2             0.2906   0.2291
2024-S1             0.2969      NaN
2024-S2             0.2941   0.2573
2025-S1             0.2949      NaN
2025-S2             0.2942   0.2854

### Data begins from 2017. Checking different configuration of filters.

In [24]:
selected_tax = filtered_df["tax"].isin(["I_TAX"])
selected_currency = filtered_df["currency"].isin(["EUR"])
selected_nrg = filtered_df["nrg_cons"].isin(["KWH2500-4999"])

filtered_df_detailed = filtered_df[
    selected_tax &
    selected_currency &
    selected_nrg
]

filtered_df_detailed.head(2)

,freq,siec,nrg_cons,unit,tax,currency,geo\TIME_PERIOD,2007-S1,2007-S2,2008-S1,...,2021-S1,2021-S2,2022-S1,2022-S2,2023-S1,2023-S2,2024-S1,2024-S2,2025-S1,2025-S2
382,S,E7000,KWH2500-4999,KWH,I_TAX,EUR,EU27_2020,0.1826,0.1537,0.1604,...,0.2203,0.2415,0.2490,0.2768,0.2887,0.2847,0.2916,0.2887,0.2879,0.2896
401,S,E7000,KWH2500-4999,KWH,I_TAX,EUR,PL,NaN,0.1380,0.1259,...,0.1548,0.1574,0.1464,0.1604,0.1769,0.2162,0.2090,0.2477,0.2559,0.2709

In [25]:
filtered_df_detailed.T

                          382           401
freq                        S             S
siec                    E7000         E7000
nrg_cons         KWH2500-4999  KWH2500-4999
unit                      KWH           KWH
tax                     I_TAX         I_TAX
currency                  EUR           EUR
geo\TIME_PERIOD     EU27_2020            PL
2007-S1                0.1826           NaN
2007-S2                0.1537         0.138
2008-S1                0.1604        0.1259
2008-S2                0.1676        0.1295
2009-S1                 0.167        0.1131
2009-S2                0.1677        0.1291
2010-S1                0.1725        0.1341
2010-S2                0.1777        0.1382
2011-S1                0.1858        0.1471
2011-S2                0.1886        0.1351
2012-S1                0.1916        0.1418
2012-S2                0.1996        0.1529
2013-S1                0.2042         0.148
2013-S2                0.2062        0.1437
2014-S1                0.2058        0.1421
2014-S2                0.2084        0.1408
2015-S1                0.2083        0.1444
2015-S2                0.2089        0.1418
2016-S1                0.2051        0.1332
2016-S2                0.2069        0.1352
2017-S1                0.2089        0.1446
2017-S2                0.2089        0.1451
2018-S1                0.2103         0.141
2018-S2                0.2152        0.1396
2019-S1                0.2168        0.1343
2019-S2                0.2169        0.1376
2020-S1                0.2139        0.1475
2020-S2                0.2153         0.151
2021-S1                0.2203        0.1548
2021-S2                0.2415        0.1574
2022-S1                 0.249        0.1464
2022-S2                0.2768        0.1604
2023-S1                0.2887        0.1769
2023-S2                0.2847        0.2162
2024-S1                0.2916         0.209
2024-S2                0.2887        0.2477
2025-S1                0.2879        0.2559
2025-S2                0.2896        0.2709

### Data looks fine. Verifying whether there are missings.

In [26]:
filtered_df_detailed.isna().sum()

freq               0
siec               0
nrg_cons           0
unit               0
tax                0
currency           0
geo\TIME_PERIOD    0
2007-S1            1
2007-S2            0
2008-S1            0
2008-S2            0
2009-S1            0
2009-S2            0
2010-S1            0
2010-S2            0
2011-S1            0
2011-S2            0
2012-S1            0
2012-S2            0
2013-S1            0
2013-S2            0
2014-S1            0
2014-S2            0
2015-S1            0
2015-S2            0
2016-S1            0
2016-S2            0
2017-S1            0
2017-S2            0
2018-S1            0
2018-S2            0
2019-S1            0
2019-S2            0
2020-S1            0
2020-S2            0
2021-S1            0
2021-S2            0
2022-S1            0
2022-S2            0
2023-S1            0
2023-S2            0
2024-S1            0
2024-S2            0
2025-S1            0
2025-S2            0
dtype: int64

### There is only one missing in 2007. However, I want to keep year 2007.

### Creating a copy of the dataframe, and continuing the transformation.

In [27]:
electricity_df = filtered_df_detailed.copy()

In [28]:
electricity_df.head(2)

,freq,siec,nrg_cons,unit,tax,currency,geo\TIME_PERIOD,2007-S1,2007-S2,2008-S1,...,2021-S1,2021-S2,2022-S1,2022-S2,2023-S1,2023-S2,2024-S1,2024-S2,2025-S1,2025-S2
382,S,E7000,KWH2500-4999,KWH,I_TAX,EUR,EU27_2020,0.1826,0.1537,0.1604,...,0.2203,0.2415,0.2490,0.2768,0.2887,0.2847,0.2916,0.2887,0.2879,0.2896
401,S,E7000,KWH2500-4999,KWH,I_TAX,EUR,PL,NaN,0.1380,0.1259,...,0.1548,0.1574,0.1464,0.1604,0.1769,0.2162,0.2090,0.2477,0.2559,0.2709

### Changing wide format into long format. For that purpose melt function will be used.

In [29]:
# Select period columns (2007-2024) and exclude incomplete 2025 data
period_columns = []

for col in electricity_df.columns:
    if col.startswith("2") and not col.startswith("2025"):
        period_columns.append(col)

print(period_columns)

['2007-S1', '2007-S2', '2008-S1', '2008-S2', '2009-S1', '2009-S2', '2010-S1', '2010-S2', '2011-S1', '2011-S2', '2012-S1', '2012-S2', '2013-S1', '2013-S2', '2014-S1', '2014-S2', '2015-S1', '2015-S2', '2016-S1', '2016-S2', '2017-S1', '2017-S2', '2018-S1', '2018-S2', '2019-S1', '2019-S2', '2020-S1', '2020-S2', '2021-S1', '2021-S2', '2022-S1', '2022-S2', '2023-S1', '2023-S2', '2024-S1', '2024-S2']

In [30]:
electricity_melted_df = electricity_df.melt(
    id_vars=['geo\\TIME_PERIOD'],
    value_vars = period_columns,
    var_name='period',
    value_name = 'electricity_price'
)

In [31]:
electricity_melted_df.shape

(72, 3)

In [32]:
#final_electricity_df.to_csv("../data/processed/electricity_prices_poland_eu.csv",
                            #index = False
                           #)

In [33]:
electricity_melted_df.head(10)

  geo\TIME_PERIOD   period  electricity_price
0       EU27_2020  2007-S1             0.1826
1              PL  2007-S1                NaN
2       EU27_2020  2007-S2             0.1537
3              PL  2007-S2             0.1380
4       EU27_2020  2008-S1             0.1604
5              PL  2008-S1             0.1259
6       EU27_2020  2008-S2             0.1676
7              PL  2008-S2             0.1295
8       EU27_2020  2009-S1             0.1670
9              PL  2009-S1             0.1131

### After melt function there are 72 rows (2 countries with 36 rows with period 2007-S1 until 2024-S2 were melted into 72 rows as each period becomes separated row). There are also 3 columns: 'geo\TIME_PERIOD,'period', and 'electricity_price'. Changing name of first column to 'country', as this is more readible.

In [34]:
electricity_melted_df.rename(columns={'geo\\TIME_PERIOD':
'country'},inplace=True)

In [35]:
electricity_melted_df.head(10)

     country   period  electricity_price
0  EU27_2020  2007-S1             0.1826
1         PL  2007-S1                NaN
2  EU27_2020  2007-S2             0.1537
3         PL  2007-S2             0.1380
4  EU27_2020  2008-S1             0.1604
5         PL  2008-S1             0.1259
6  EU27_2020  2008-S2             0.1676
7         PL  2008-S2             0.1295
8  EU27_2020  2009-S1             0.1670
9         PL  2009-S1             0.1131

### Separating number from semester in period column.

In [36]:
electricity_melted_df["year"] = electricity_melted_df["period"].str.split("-").str[0]
electricity_melted_df["semester"] = electricity_melted_df["period"].str.split("-").str[1]

print(electricity_melted_df)

      country   period  electricity_price  year semester
0   EU27_2020  2007-S1             0.1826  2007       S1
1          PL  2007-S1                NaN  2007       S1
2   EU27_2020  2007-S2             0.1537  2007       S2
3          PL  2007-S2             0.1380  2007       S2
4   EU27_2020  2008-S1             0.1604  2008       S1
..        ...      ...                ...   ...      ...
67         PL  2023-S2             0.2162  2023       S2
68  EU27_2020  2024-S1             0.2916  2024       S1
69         PL  2024-S1             0.2090  2024       S1
70  EU27_2020  2024-S2             0.2887  2024       S2
71         PL  2024-S2             0.2477  2024       S2

[72 rows x 5 columns]

### Removing period column, as it is no longer needed.

In [37]:
electricity_melted_df.drop("period",axis = 1, inplace = True)
print(electricity_melted_df)

      country  electricity_price  year semester
0   EU27_2020             0.1826  2007       S1
1          PL                NaN  2007       S1
2   EU27_2020             0.1537  2007       S2
3          PL             0.1380  2007       S2
4   EU27_2020             0.1604  2008       S1
..        ...                ...   ...      ...
67         PL             0.2162  2023       S2
68  EU27_2020             0.2916  2024       S1
69         PL             0.2090  2024       S1
70  EU27_2020             0.2887  2024       S2
71         PL             0.2477  2024       S2

[72 rows x 4 columns]

In [38]:
electricity_melted_df.isna().sum()

country              0
electricity_price    1
year                 0
semester             0
dtype: int64

In [39]:
electricity_melted_df.dtypes

country               object
electricity_price    float64
year                  object
semester              object
dtype: object

### Grouping the data.

In [40]:
electricity_grouped_df = electricity_melted_df.groupby(["country", "year"])[["electricity_price"]].mean()

In [41]:
electricity_grouped_df.head(20)

                electricity_price
country   year
EU27_2020 2007            0.16815
          2008            0.16400
          2009            0.16735
          2010            0.17510
          2011            0.18720
          2012            0.19560
          2013            0.20520
          2014            0.20710
          2015            0.20860
          2016            0.20600
          2017            0.20890
          2018            0.21275
          2019            0.21685
          2020            0.21460
          2021            0.23090
          2022            0.26290
          2023            0.28670
          2024            0.29015
PL        2007            0.13800
          2008            0.12770

In [42]:
type(electricity_grouped_df)

pandas.core.frame.DataFrame

In [43]:
type(electricity_grouped_df.index)

pandas.core.indexes.multi.MultiIndex

### Reseting MultiIndex back to "normal index" with normal columns and default digital index and limiting decimals to 4 places.

In [45]:
electricity_grouped_df.reset_index()

      country  year  electricity_price
0   EU27_2020  2007            0.16815
1   EU27_2020  2008            0.16400
2   EU27_2020  2009            0.16735
3   EU27_2020  2010            0.17510
4   EU27_2020  2011            0.18720
5   EU27_2020  2012            0.19560
6   EU27_2020  2013            0.20520
7   EU27_2020  2014            0.20710
8   EU27_2020  2015            0.20860
9   EU27_2020  2016            0.20600
10  EU27_2020  2017            0.20890
11  EU27_2020  2018            0.21275
12  EU27_2020  2019            0.21685
13  EU27_2020  2020            0.21460
14  EU27_2020  2021            0.23090
15  EU27_2020  2022            0.26290
16  EU27_2020  2023            0.28670
17  EU27_2020  2024            0.29015
18         PL  2007            0.13800
19         PL  2008            0.12770
20         PL  2009            0.12110
21         PL  2010            0.13615
22         PL  2011            0.14110
23         PL  2012            0.14735
24         PL  2013            0.14585
25         PL  2014            0.14145
26         PL  2015            0.14310
27         PL  2016            0.13420
28         PL  2017            0.14485
29         PL  2018            0.14030
30         PL  2019            0.13595
31         PL  2020            0.14925
32         PL  2021            0.15610
33         PL  2022            0.15340
34         PL  2023            0.19655
35         PL  2024            0.22835

In [49]:
electricity_grouped_df = electricity_grouped_df["electricity_price"].round(4)

In [50]:
electricity_grouped_df.head(10)

country    year
EU27_2020  2007    0.1682
           2008    0.1640
           2009    0.1674
           2010    0.1751
           2011    0.1872
           2012    0.1956
           2013    0.2052
           2014    0.2071
           2015    0.2086
           2016    0.2060
Name: electricity_price, dtype: float64

## Save processed dataset.

In [52]:
electricity_grouped_df.to_csv("../data/processed/electricity_prices_poland_eu.csv")